# Generated by Django 4.2.17 on 2024-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_remove_reservation_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='content',
        ),
        migrations.AddField(
            model_name='home',
            name='dish',
            field=models.TextField(default='food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='menu',
            field=models.CharField(default='menu', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slogan',
            field=models.TextField(default='slogan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
