# Generated by Django 4.2.17 on 2024-12-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_body_home_description_remove_home_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='home',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='home',
            name='menu',
        ),
    ]
