# Generated by Django 4.2.17 on 2024-12-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_description_home_content_remove_home_dish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='content',
        ),
    ]
