# Generated by Django 4.2.17 on 2024-12-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_table_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
