# Generated by Django 4.2.17 on 2025-01-02 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='noreply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(default='Default message'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
