# Generated by Django 4.2.17 on 2025-01-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_date_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Unnamed Reservation', max_length=100),
        ),
    ]
