# Generated by Django 4.2.17 on 2025-01-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
    ]
