# Generated by Django 4.2.17 on 2025-01-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_reservation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
