# Generated by Django 4.2.17 on 2025-01-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_alter_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='customer',
        ),
    ]
